"""add_unique_constraint_to_recipe

Revision ID: d423b0c684dd
Revises: 
Create Date: 2025-01-12 20:27:47.957268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd423b0c684dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('job', sa.String(length=3), nullable=True),
    sa.Column('recipe_level', sa.Integer(), nullable=True),
    sa.Column('master_book_level', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('patch_version', sa.String(length=10), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'job', name='uix_recipe_name_job')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_index(op.f('ix_recipes_job'), 'recipes', ['job'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_recipe_level'), 'recipes', ['recipe_level'], unique=False)
    op.create_table('recipe_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_durability', sa.Integer(), nullable=True),
    sa.Column('max_quality', sa.Integer(), nullable=True),
    sa.Column('required_durability', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('required_craftsmanship', sa.Integer(), nullable=True),
    sa.Column('required_control', sa.Integer(), nullable=True),
    sa.Column('progress_per_100', sa.Float(), nullable=True),
    sa.Column('quality_per_100', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_data')
    op.drop_table('recipe_stats')
    op.drop_index(op.f('ix_recipes_recipe_level'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_job'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
